language: python
python:
  - "3.5"
  - "3.6"
sudo: true
env:
  - DB_PWD="travis_db_pwd"
  - USE_TRAVIS=true
services:
  - mysql
before_script:
  - sudo mysql -e 'create database wechat_ticket;'
  - python manage.py syncdb --noinput
install:
  - pip install -r requirements.txt
script: true