language: python
python:
  - "3.5"
sudo: true
env:
  global:
    - DB_PWD="travis_db_pwd"
    - USE_TRAVIS=true
services:
  - mysql
before_script:
  - sudo mysql -e 'create database wechat_ticket;'
install:
  - pip install -r requirements.txt
  - python manage.py makemigrations
  - python manage.py migrate
script: true