version: '3'

services:
  db:
    image: mysql:5.7.19
    expose:
      - "3306"
    volumes:
      - ./db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  web:
    restart: always
    build: .
    environment:
      ADMIN: ${ADMIN}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    command: ["./wait-for-it.sh", "db:3306", "--", "./start_django.sh"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db